###############
# Install Git #
###############

###################
# Requirements:   #
# * gcc-c++       #
# * curl-devel    #
# * expat-devel   #
# * gettext-devel #
# * openssl-devel #
# * zlib-devel    #
###################

# Detect git's presence
- stat: path={{STOW_PATH}}/../bin/git
  register: git_bin
  changed_when: git_bin.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.git}}", pkg_check: "{{git_bin}}" }

- name: Install Git
  when: git_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make prefix={{STOW_PATH}}/{{src_folder.stdout}} all doc info;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    ./{{src_folder.stdout}}/bin/stow {{src_folder.stdout}}"
  notify:
    - source bash

- shell: "{{src_bash}} git --version"
  register: git_version
  changed_when: "git_version.rc != 0"

- name: Display git version
  debug: msg="{{git_version.stdout}}"
