---
- name: Set sysadmin user's $HOME variable
  shell: chdir=~ pwd
  register: HOME
  ignore_errors: yes
  changed_when: "HOME.rc != 0"

####################
# Install GNU Stow #
####################
- include: stow.yml

######################
# Available Packages #
#############@@#######
- include: git.yml
