---
- name: Set ${sysadmins}'s $HOME variable
  command: chdir=~ pwd
  register: HOME
  ignore_errors: True

- name: Create STOW directory
  command: mkdir -p {{STOW_PATH}} creates={{STOW_PATH}}/.ansible_keep

- name: Prevent 'changed' status on STOW dir creation
  command: touch {{STOW_PATH}}/.ansible_keep creates={{STOW_PATH}}/.ansible_keep

- name: ensure $STOW is defined
  lineinfile:
    dest={{HOME.stdout}}/.bashrc
    regexp="^export STOW={{STOW_PATH}}$"
    line="export STOW={{STOW_PATH}}"
    state=present
    insertafter=EOF
    create=True
#  notify:
#    - source bash

- name: Ensure Stow's bin has precedence over $PATH
  lineinfile:
    dest={{HOME.stdout}}/.bashrc
    regexp="^export PATH=.*STOW.*:.*PATH"
    line="export PATH=${STOW}/../bin:${PATH}"
    state=present
    insertafter=EOF
    create=True
#  notify:
#    - source bash
