---
- name: Set sysadmin user's $HOME variable
  shell: chdir=~ pwd
  register: HOME
  ignore_errors: yes
  changed_when: "HOME.rc != 0"

###################
# Define ENV Vars #
###################
- include: env.yml

####################
# Install GNU Stow #
####################
- include: stow.yml

######################
# Available Packages #
######################
# Installs: libevent, ncurses, tmux
- include: tmux.yml
- include: openssl.yml # Because cryptography
# Needs: gcc-c++ curl-devel expat-devel gettext-devel openssl-devel zlib-devel
#- include: git.yml
