###################
# Install ncurses #
###################

###################
# Requirements:   #
# * gcc-c++       #
###################

# Detect ncurses
- stat: path={{STOW_PATH}}/../share/terminfo
  register: ncurses_bin
  changed_when: ncurses_bin.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.ncurses}}", pkg_check: "{{ncurses_bin}}" }

- name: Install ncurses
  when: ncurses_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}}"
  register: ncurses_install
  changed_when: ncurses_install.rc != 0 or ncurses_bin.stat.exists == False

- shell: "{{src_bash}} ncurses5-config --version"
  register: ncurses_version
  changed_when: ncurses_version.rc != 0 or ncurses_bin.stat.exists == False

- name: Display ncurses version
  debug: msg="{{ncurses_version.stdout}}"
  failed_when: '"{{src.ncurses.ver}}" not in ncurses_version.stdout'
