###################
# Install openssl #
###################

###################
# Requirements:   #
# * gcc-c++       #
###################

# Detect openssl
- stat: path={{STOW_PATH}}/../bin/openssl
  register: openssl_bin
  changed_when: openssl_bin.stat.exists == False

# Upload & extract source
- { include: upload_src.yml, package: "{{src.openssl}}", pkg_check: "{{openssl_bin}}" }

- name: Install openssl
  when: openssl_bin.stat.exists == False
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./config --prefix={{STOW_PATH}}/{{src_folder.stdout}} \
      --openssldir=ssl --libdir=lib shared;
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    creates {{STOW_PATH}}/../bin/openssl;"
  register: openssl_install
  changed_when: openssl_install.rc != 0 or openssl_bin.stat.exists == False
  ignore_errors: True

- shell: "{{src_bash}} openssl version"
  register: openssl_version
  changed_when: openssl_version.rc != 0 or openssl_bin.stat.exists == False

- name: Display openssl version
  debug: msg="{{openssl_version.stdout}}"
  failed_when: '"{{src.openssl.ver}}" not in openssl_version.stdout'
