####################
# Install GNU Stow #
####################

- name: Create expected directories | [STOW, SRC]
  file: path={{item}} state=directory
  with_items:
    - "{{STOW_PATH}}"
    - "{{SRC_PATH}}"

- name: Ensure $STOW is defined
  lineinfile:
    dest={{HOME.stdout}}/.bashrc
    regexp="^export STOW={{STOW_PATH}}$"
    line="export STOW={{STOW_PATH}}"
    state=present
    insertafter=EOF
    create=True
  notify:
    - source bash

- name: Ensure stow's bin has precedence over $PATH
  lineinfile:
    dest={{HOME.stdout}}/.bashrc
    regexp="^export PATH=.*STOW.*:.*PATH"
    line="export PATH=${STOW}/../bin:${PATH}"
    state=present
    insertafter=EOF
    create=True

- name: Ensure $SRC is defined
  lineinfile:
    dest={{HOME.stdout}}/.bashrc
    regexp="^export SRC={{SRC_PATH}}$"
    line="export SRC={{SRC_PATH}}"
    state=present
    insertafter=EOF
    create=True
  notify:
    - source bash

# Detect stow's presence
- stat: path={{STOW_PATH}}/../bin/stow
  register: stow_bin

- command: echo "{{src.stow.name}}-{{src.stow.ver}}.{{src.stow.ext}}"
  register: src_file_name
  changed_when: false

- command: echo "{{src.stow.name}}-{{src.stow.ver}}"
  register: src_folder
  changed_when: false

- name: Copy stow's source file to remote node
  when: stow_bin.stat.exists == false
  unarchive: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}/{{src_folder.stdout}}
  #copy: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}/{{src_file_name.stdout}} owner={{sysadmin}} mode=0644

- name: Install GNU Stow
  when: stow_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    ./{{src_folder.stdout}}/bin/stow {{folder}}"
  notify:
    - source bash

- shell: "{{src_bash}} stow --version"
  register: stow_version
  changed_when: "stow_version.rc != 0"

- name: Display stow version
  debug: msg="{{stow_version.stdout}}"
