################
# Install Tmux #
################

####################
# Requirements:    #
# * gcc-c++        #
# * ncurses-5.9    #
# * libevent-2.1.0 #
####################

# Detect tmux's presence
- stat: path={{STOW_PATH}}/../bin/tmux
  register: tmux_bin
  changed_when: tmux_bin.stat.exists == False

# Upload & extract source
- { include: upload_src.yml, package: "{{src.tmux}}", pkg_check: "{{tmux_bin}}" }

- name: Install Tmux
  when: tmux_bin.stat.exists == False
  shell:
    '{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure CFLAGS="-I{{STOW_PATH}}/../include -I{{STOW_PATH}}/../include/ncurses" LDFLAGS="-I{{STOW_PATH}}/../lib -L{{STOW_PATH}}/../include/ncurses -L{{STOW_PATH}}/../include" CPPFLAGS="-I{{STOW_PATH}}/../include -I{{STOW_PATH}}/../include/ncurses" LDFLAGS="-static -L{{STOW_PATH}}/../include -L{{STOW_PATH}}/../include/ncurses -L{{STOW_PATH}}/../lib";
    make;
    mkdir -p {{STOW_PATH}}/{{src_folder.stdout}}/bin;
    cp tmux {{STOW_PATH}}/{{src_folder.stdout}}/bin;
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};'
  register: tmux_install
  changed_when: tmux_install.rc != 0 or tmux_bin.stat.exists == False

- shell: "{{src_bash}} tmux -V"
  register: tmux_version
  changed_when: tmux_version.rc != 0 or tmux_bin.stat.exists == False

- name: Display tmux version
  debug: msg="{{tmux_version.stdout}}"
  failed_when: '"{{src.tmux.ver}}" not in tmux_version.stdout'
