---
########################
# Install Ruby via RVM #
########################

#################
# Requirements: #
# * curl        #
#################

- include: rvm.yml
- include: rvm_packages.yml
- include: rvm_ruby.yml

#######################
# Install vim w/ Ruby #
#######################

- include: vim.yml
