- name: Install RVM Packages for Rubies
  when: rvm_fw.packages != False
  shell: "{{src_bash}} rvm pkg install {{item}}"
  with_items: rvm_fw.packages
  register: rvm_pkg_tmp
  changed_when: rvm_pkg_tmp.rc != 0
