####################
# Install Apache 2 #
####################

###################
# Requirements:   #
# * gcc-c++       #
###################

- include: apr.yml
- include: apr-util.yml
- include: pcre.yml

# Detect httpd
- stat: path={{STOW_PATH}}/../bin/httpd
  register: httpd_bin
  changed_when: httpd_bin.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.httpd}}", pkg_check: "{{httpd_bin}}" }

- name: Install httpd
  when: httpd_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    creates={{STOW_PATH}}/../bin/httpd;"

# Verify httpd installed
- shell: "{{src_bash}} httpd -v"
  register: httpd_version
  changed_when: httpd_version.rc != 0

- name: Display httpd version
  debug: msg="{{httpd_version.stdout}}"
