###############
# Install apr #
###############

#################
# Requirements: #
# * gcc-c++     #
#################

# Detect apr
- stat: path={{STOW_PATH}}/../bin/apr-1-config
  register: apr_bin
  changed_when: apr_bin.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.apr}}", pkg_check: "{{apr_bin}}" }

- name: Install apr
  when: apr_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    creates={{STOW_PATH}}/../bin/apr-1-config;"

# Verify apr installed
- shell: "{{src_bash}} apr-1-config --version"
  register: apr_version
  changed_when: apr_version.rc != 0

- name: Display apr version
  debug: msg="{{apr_version.stdout}}"
