###############
# Install apr #
###############

#################
# Requirements: #
# * gcc-c++     #
#################

- { include: set_src_vars.yml, package: "{{src.apr}}" }

# Detect apr
- stat: path={{STOW_PATH}}/../bin/apr-1-config
  register: apr_bin
  changed_when: apr_bin.stat.exists == false

- name: Create apr src directory
  when: apr_bin.stat.exists == false
  command: mkdir -p {{SRC_PATH}}/{{src_folder.stdout}} creates={{SRC_PATH}}/{{src_folder.stdout}}

- name: Copy apr src file to remote node
  when: apr_bin.stat.exists == false
#  unarchive: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}/{{src_folder.stdout}}
  copy: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}/{{src_file_name.stdout}} owner={{sysadmin}} mode=0644

- name: Install apr
  when: apr_bin.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}};
    tar -xjf {{src_file_name.stdout}};
    cd {{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    creates={{STOW_PATH}}/../bin/apr-1-config;"

# Verify apr installed
- shell: "{{src_bash}} apr-1-config --version"
  register: apr_version
  changed_when: apr_version.rc != 0

- name: Display apr version
  debug: msg="{{apr_version.stdout}}"
