################
# Install pcre #
################

#################
# Requirements: #
# * gcc-c++     #
#################

# Detect pcre
- stat: path={{STOW_PATH}}/../bin/pcre-config
  register: pcre_config
  changed_when: pcre_config.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.pcre}}", pkg_check: "{{pcre_config}}" }

- name: Install pcre
  when: pcre_config.stat.exists == false
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}};
    tar -xzf {{src_file_name.stdout}};
    cd {{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    creates={{STOW_PATH}}/../bin/pcre-config;"

# Verify pcre installed
- shell: "{{src_bash}} pcre-config --version"
  register: pcre_version
  changed_when: pcre_version.rc != 0

- name: Display pcre version
  debug: msg="{{pcre_version.stdout}}"
