---
  - name: Determine username
    action: shell whoami
    register: whoami

  # "> " puts yaml in quote mode and enables : chars in output
  - name: Debug which user is running the tasks
    debug: >
      msg="Logged in as: {{ whoami.stdout }}"
