################
# Install rack #
################

- command: echo "grep 'rack ('"
  register: grep_rack
  changed_when: False

- name: Detect rack
  shell: 'bash -l -c "gem list | {{grep_rack.stdout}}"'
  register: rack_gem
  changed_when: rack_gem.rc != 0
  ignore_errors: True

- name: Install rack gem
  when: rack_gem|failed
  shell: 'bash -l -c "gem install rack"'
  register: rack_install
  ignore_errors: True

# Detect rack version
- shell: "bash -l -c 'rackup --version'"
  register: rack_version
  changed_when: rack_version.rc != 0

- name: Display rack version
  debug: msg="{{rack_version.stdout}}"
  failed_when: rack_version.rc != 0
