# Detect bzip2's presence
- stat: path={{STOW_PATH}}/../bin/bzip2
  register: bzip2_bin
  changed_when: bzip2_bin.stat.exists == False

# Upload & extract source
- { include: upload_src.yml, package: "{{src.bzip2}}", pkg_check: "{{bzip2_bin}}" }

- name: Setup & compile bzip2
  when: bzip2_bin.stat.exists == False
  shell: '{{src_bash}}
         cd {{SRC_PATH}}/{{src_folder.stdout}};
         make -f Makefile-libbz2_so;
         make;
         make install PREFIX={{STOW_PATH}}/{{src_folder.stdout}};
         cp libbz2.so.{{src.bzip2.ver}} {{STOW_PATH}}/{{src_folder.stdout}}/lib;
         cd {{STOW_PATH}};
         stow {{src_folder.stdout}};'
  register: bzip2_install
  changed_when: bzip2_install.rc != 0 or bzip2_bin.stat.exists == False

- stat: path={{STOW_PATH}}/../bin/bzip2
  register: bzip2
  changed_when: bzip2_bin.stat.exists == False
  failed_when: bzip2.stat.exists == False

- name: Display bzip2 symlink source
  debug: msg="{{bzip2.stat.lnk_source}}"
  failed_when: '"{{src.bzip2.ver}}" not in bzip2.stat.lnk_source'
