################
# Setup Python #
################

################
# Requirements #
# * gcc-c++    #
################

# Detect python's presence
- stat: path={{STOW_PATH}}/../bin/python
  register: python_bin
  changed_when: python_bin.stat.exists == false

# Upload & extract source
- { include: upload_src.yml, package: "{{src.python}}", pkg_check: "{{python_bin}}" }

- name: Install Python
  when: python_bin.stat.exists == false
  shell: '{{src_bash}}
    export CLFLAGS="-fPIC";
    export C_INCLUDE_PATH={{STOW_PATH}}/../include;
    export CPLUS_INCLUDE_PATH=${C_INCLUDE_PATH};
    export LIBRARY_PATH={{STOW_PATH}}/../lib;
    export LD_RUN_PATH=${LIBRARY_PATH};
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}} --libdir={{STOW_PATH}}/../lib --enable-shared;
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};'
  register: python_install

- shell: "{{src_bash}} python -V"
  register: python_version
  changed_when: python_version.rc != 0

- debug: msg="{{python_version.stdout}}"

- name: Display Python version
  debug: msg="{{python_version.stdout}}"

- name: Verify bzip2 module works
  shell: '{{src_bash}} python -c "import bz2; print bz2.__doc__"'
  register: py_bzip2_result
  changed_when: "'python bz2 module' not in py_bzip2_result.stdout"

- debug: msg="{{py_bzip2_result.stdout}}"
