---
- hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap a legacy python 2.4 host
      raw: yum -y install python-simplejson
      sudo: True
  tasks:
    - name: Install expected compiler packages for Ruby
      yum: pkg=$item state=latest
      with_items:
        - gcc-c++
        - make
#        - glibc
#        - patch
#        - readline
#        - readline-devel
#        - zlib
#        - zlib-devel
#        - libyaml-devel
#        - libffi-devel
#        - openssl-devel
#        - bzip2
#        - autoconf
#        - automake
#        - libtool
#        - bison
#        - git-core
