---
# This playbook deploys the whole infrastructure stack for this application

#  Uncomment this playbook if you need to debug basic user information
#- name: Verify who's running commands via debug
#  hosts: all
#  sudo: True
#  sudo_user: "{{sysadmin}}"
#  roles:
#    - debug

- name: Initialize all SUPPORT servers
  vars_files:
  - group_vars/all.yml
  hosts: all
  sudo: yes
  sudo_user: "{{sysadmin}}"
  roles:
    - common

- name: Setup the Ruby environment
  vars_files:
  - group_vars/all.yml
  hosts: ruby:rails
  sudo_user: "{{sysadmin}}"
  sudo: yes
  roles:
    - ruby

- name: Setup the webserver infrastructure
  hosts: web
  sudo_user: "{{sysadmin}}"
  vars_files:
  - group_vars/all.yml
#  vars_prompt:
#    ssl_passphrase: "Please enter the passphrase for the SSL certificate"
  roles:
    - web

#- name: Setup the DB infrastructure
#  hosts: db
#  sudo_user: "{{sysadmin}}"
#  user: #  roles: #    - db

#- name: Setup the Rails environment
#  hosts: rails
#  sudo_user: "{{sysadmin}}"
#  sudo: yes
#  roles:
#    - rails
