---
###############################
# Rack Web Server Integration #
###############################

- include: passenger.yml
- { include: rack_app.yml, app: "{{apps.example}}", when: apps.example.enabled == True }
